name: DataIngest CI - Infrastructure

on:
  push:
    branches: [main]
    paths:
      - "infrastructure/DataIngest/**"
  pull_request:
    branches: [main]
    paths:
      - "infrastructure/DataIngest/**"

  workflow_dispatch:

env:
  TF_DIRECTORY: "/infrastructure/DataIngest"
  TF_STATESTOR_NAME: "azappdemostate"
  TF_STATESTOR_GROUP: "AzureAppDemo-state"
  TF_STATESTOR_CONTAINER: "tfstate"

jobs:
  build:
    name: Set up infrastructure for DataIngest applications
    runs-on: ubuntu-latest

    steps:
      - name: Install terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Format
        run: terraform fmt

      - name: Checkout terraform files
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        run: |
          cd ${{ env.TF_DIRECTORY }}
          terraform init

      - name: Terraform Validate
        run: terraform validate -no-color

      - name: Configure Terraform
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
            STATE_ACCOUNT_KEY=$(az storage account keys list -g ${{ env.TF_STATESTOR_GROUP }} --account-name ${{ env.TF_STATESTOR_NAME }} --query '[0].value -o tsv')
            export TF_ACCESS_KEY=$STATE_ACCOUNT_KEY

      - name: Terraform Plan
        run: terraform plan -no-color

      - name: Terraform Apply
        run: terraform apply
