name: IngestFunc CI - Application

on:
  push:
    branches: [main]
    paths:
      - "applications/DataIngest/IngestFunc/**"
  pull_request:
    branches: [main]
    paths:
      - "applications/DataIngest/IngestFunc/**"

  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: "DataIngestFunc"
  APP_DIRECTORY: "./applications/DataIngest/IngestFunc"
  DOTNET_VERSION: "3.1.x"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout IngestFunc"
        uses: actions/checkout@v2

      - name: "Setup dotnet environment"
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: "Restore project and dependencies"
        shell: bash
        run: |
          cd ${{ env.APP_DIRECTORY }}
          dotnet restore
          dotnet build --configuration Release --output './publish'

      - name: "Deploy to Azure Function"
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ AZURE_FUNCTIONAPP_NAME }}
          package: "${{ APP_DIRECTORY }}/publish"
          publish-profile: ${{ secrets.AZURE_CREDENTIALS }}
